---
title: "tf_gnn_buildingblocks"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
    number_sections: true
vignette: >
  %\VignetteIndexEntry{tf_gnn_example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r}
#| label: "rsetup"
#| include: true
#| eval: true
library(reticulate)
#use_virtualenv("C://Users//fil44768//OneDrive - GSK//Documents//.virtualenvs//gnn", required=TRUE)
use_virtualenv("/Users/work/pyollama", required = TRUE)
```

```{r}
#| label: "create_example1"
#| include: true
#| eval: true
library(synthpop)
library(kableExtra)

cat("##----------------------------------------------------------------------------##\n")
cat("##----------------------------------------------------------------------------##\n\n")
cat("Simple summaries: means BMI, height, weight, \n")
cat("mean BMI=",mean(SD2011$bmi, na.rm = TRUE),"\n")
cat("mean height=",mean(SD2011$height, na.rm = TRUE),"\n")
cat("mean weight=",mean(SD2011$weight, na.rm = TRUE),"\n")

ex1_res<-list(mean_bmi=mean(SD2011$bmi, na.rm = TRUE),
              mean_heght=mean(SD2011$height, na.rm = TRUE),
              mean_weight=mean(SD2011$weight, na.rm = TRUE))

ex2<-table(SD2011$smoke,SD2011$sport,useNA="no")


mask<- SD2011$sex=="FEMALE" & SD2011$edu=="SECONDARY"
ex3<-table(SD2011$smoke[mask],SD2011$sport[mask],dnn=c("Smoker","Sport"),useNA="no")

cat("##----------------------------------------------------------------------------##\n\n")

cat("Smoking v Sport activity in Females with Secondary Education\n")
cat("##----------------------------------------------------------------------------##\n\n")
cat("1a. Frequency counts\n")
print(ex3)
cat("\n1b. Row %\n")
print(ex3_row<-ex3[,]/apply(ex3,1,sum))
cat("\n1c. Col %\n")
print(t(ex3_col<-t(t(ex3[,])/apply(ex3,2,sum))))
#cat("\n1d. Chi-squared test for independence p-value %\n")
#cat("p-value=",chisq.test(ex3)$p.value,"\n\n")

#Y<-as.numeric(SD2011$smoke[mask])-1
#X<-as.numeric(SD2011$sport[mask])-1;
#m1<-glm(Y~X,family="binomial")
#pval<-summary(m1)$coefficients["X","Pr(>|z|)"]

#cat("\n1e. Logistic regression p-value for Sport Coefficient\n")
#cat("p-value=",pval,"\n\n")
cat("##----------------------------------------------------------------------------##\n")

```
```{r}
#| label: "data set for passing"
#| include: true
#| eval: true
library(jsonlite)
## Instruction: You are a clinical data analyst. Analyze the following patient records and answer the query accurately.

thedata<-toJSON(head(SD2011),pretty=TRUE)
Nint<-100L
r_to_py(Nint)
```

```{python}
print(f"N={r.Nint}\n")
N=r.Nint
```

```{python}
#| label: "py1"
#| include: true
#| eval: true

import ollama
import json

model_name = 'qwen3-coder:30b' #'phi4:latest'
#model_name = 'phi4:latest'
#N=10 #no. reps

prompt = """
Instruction: You are an expert statistician and programmer. Analyze the following patient records and answer the query accurately. 

Data:
[
  {
    "sex": "FEMALE",
    "age": 57,
    "agegr": "45-59",
    "placesize": "URBAN 100,000-200,000",
    "region": "Lubuskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "services for the population and transport services",
    "socprof": "RETIRED",
    "unempdur": 0,
    "income": 800,
    "marital": "MARRIED",
    "mmarr": 10,
    "ymarr": 1979,
    "ls": "PLEASED",
    "depress": 6,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "NO",
    "sport": "NO",
    "nofriend": 6,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 170,
    "weight": 89,
    "bmi": 30.7958
  },
  {
    "sex": "MALE",
    "age": 20,
    "agegr": "16-24",
    "placesize": "RURAL AREAS",
    "region": "Podlaskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": -8,
    "income": 350,
    "marital": "SINGLE",
    "ls": "MOSTLY SATISFIED",
    "depress": 0,
    "trust": "IT`S DIFFICULT TO TELL",
    "trustfam": "YES",
    "trustneigh": "NO OPINION",
    "sport": "NO",
    "nofriend": 4,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 187,
    "weight": 82,
    "bmi": 23.4493
  },
  {
    "sex": "FEMALE",
    "age": 18,
    "agegr": "16-24",
    "placesize": "URBAN 500,000 AND OVER",
    "region": "Mazowieckie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": -8,
    "marital": "SINGLE",
    "ls": "PLEASED",
    "depress": 0,
    "trust": "MOST PEOPLE CAN BE TRUSTED",
    "trustfam": "YES",
    "trustneigh": "NO",
    "sport": "NO",
    "nofriend": 20,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 165,
    "weight": 50,
    "bmi": 18.3655
  },
  {
    "sex": "FEMALE",
    "age": 78,
    "agegr": "65+",
    "placesize": "RURAL AREAS",
    "region": "Podlaskie",
    "edu": "PRIMARY/NO EDUCATION",
    "eduspec": "no specialisation",
    "socprof": "RETIRED",
    "unempdur": -8,
    "income": 900,
    "marital": "WIDOWED",
    "mmarr": 8,
    "ymarr": 1958,
    "msepdiv": 12,
    "ysepdiv": 1997,
    "ls": "MIXED",
    "depress": 16,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "NO",
    "trustneigh": "YES",
    "sport": "YES",
    "nofriend": 0,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 160,
    "weight": 78,
    "bmi": 30.4687
  },
  {
    "sex": "FEMALE",
    "age": 54,
    "agegr": "45-59",
    "placesize": "URBAN 100,000-200,000",
    "region": "Zachodnio-pomorskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "agriculture, forestry, fishing",
    "socprof": "SELF-EMPLOYED",
    "unempdur": -8,
    "income": 1500,
    "marital": "MARRIED",
    "mmarr": 6,
    "ymarr": 1980,
    "ls": "MOSTLY SATISFIED",
    "depress": 4,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "YES",
    "sport": "YES",
    "nofriend": 6,
    "smoke": "YES",
    "nociga": 20,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 158,
    "weight": 50,
    "bmi": 20.0288
  },
  {
    "sex": "MALE",
    "age": 20,
    "agegr": "16-24",
    "placesize": "URBAN 100,000-200,000",
    "region": "Slaskie",
    "edu": "SECONDARY",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": 0,
    "income": -8,
    "marital": "SINGLE",
    "ls": "PLEASED",
    "depress": 5,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "NO OPINION",
    "sport": "NO",
    "nofriend": 10,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 165,
    "weight": 65,
    "bmi": 23.8751
  }
] 

Query: Write R code to compute the mean bmi, the mean height, the mean weight in the data set. The results should be stored in a list called "themeans". The data set is a data.frame called "SD2011". Explicitly exclude NAs from any computation. Return the R code as JSON in an element called code. Be concise. 


"""
results1 = []
for i in range(N):
    response = ollama.chat(
        model=model_name,
        format='json', # This is the magic line
        messages=[{'role': 'user', 'content': prompt}]
    )
    # Parse the string into a real Python Dictionary
    data = json.loads(response['message']['content'])
    keep = data['code']
    ##print(f"iter={i} {data['code']}\n")
    results1.append(keep)

```


```{python}
#| label: "py2"
#| include: true
#| eval: true

import ollama
import json

model_name = 'qwen3-coder:30b' #'phi4:latest'
#model_name = 'phi4:latest'

#N=10 #no. reps

prompt = """
Instruction: You are an expert statistician and programmer. Analyze the following patient records and answer the query accurately. 

Data:
[
  {
    "sex": "FEMALE",
    "age": 57,
    "agegr": "45-59",
    "placesize": "URBAN 100,000-200,000",
    "region": "Lubuskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "services for the population and transport services",
    "socprof": "RETIRED",
    "unempdur": 0,
    "income": 800,
    "marital": "MARRIED",
    "mmarr": 10,
    "ymarr": 1979,
    "ls": "PLEASED",
    "depress": 6,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "NO",
    "sport": "NO",
    "nofriend": 6,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 170,
    "weight": 89,
    "bmi": 30.7958
  },
  {
    "sex": "MALE",
    "age": 20,
    "agegr": "16-24",
    "placesize": "RURAL AREAS",
    "region": "Podlaskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": -8,
    "income": 350,
    "marital": "SINGLE",
    "ls": "MOSTLY SATISFIED",
    "depress": 0,
    "trust": "IT`S DIFFICULT TO TELL",
    "trustfam": "YES",
    "trustneigh": "NO OPINION",
    "sport": "NO",
    "nofriend": 4,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 187,
    "weight": 82,
    "bmi": 23.4493
  },
  {
    "sex": "FEMALE",
    "age": 18,
    "agegr": "16-24",
    "placesize": "URBAN 500,000 AND OVER",
    "region": "Mazowieckie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": -8,
    "marital": "SINGLE",
    "ls": "PLEASED",
    "depress": 0,
    "trust": "MOST PEOPLE CAN BE TRUSTED",
    "trustfam": "YES",
    "trustneigh": "NO",
    "sport": "NO",
    "nofriend": 20,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 165,
    "weight": 50,
    "bmi": 18.3655
  },
  {
    "sex": "FEMALE",
    "age": 78,
    "agegr": "65+",
    "placesize": "RURAL AREAS",
    "region": "Podlaskie",
    "edu": "PRIMARY/NO EDUCATION",
    "eduspec": "no specialisation",
    "socprof": "RETIRED",
    "unempdur": -8,
    "income": 900,
    "marital": "WIDOWED",
    "mmarr": 8,
    "ymarr": 1958,
    "msepdiv": 12,
    "ysepdiv": 1997,
    "ls": "MIXED",
    "depress": 16,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "NO",
    "trustneigh": "YES",
    "sport": "YES",
    "nofriend": 0,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 160,
    "weight": 78,
    "bmi": 30.4687
  },
  {
    "sex": "FEMALE",
    "age": 54,
    "agegr": "45-59",
    "placesize": "URBAN 100,000-200,000",
    "region": "Zachodnio-pomorskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "agriculture, forestry, fishing",
    "socprof": "SELF-EMPLOYED",
    "unempdur": -8,
    "income": 1500,
    "marital": "MARRIED",
    "mmarr": 6,
    "ymarr": 1980,
    "ls": "MOSTLY SATISFIED",
    "depress": 4,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "YES",
    "sport": "YES",
    "nofriend": 6,
    "smoke": "YES",
    "nociga": 20,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 158,
    "weight": 50,
    "bmi": 20.0288
  },
  {
    "sex": "MALE",
    "age": 20,
    "agegr": "16-24",
    "placesize": "URBAN 100,000-200,000",
    "region": "Slaskie",
    "edu": "SECONDARY",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": 0,
    "income": -8,
    "marital": "SINGLE",
    "ls": "PLEASED",
    "depress": 5,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "NO OPINION",
    "sport": "NO",
    "nofriend": 10,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 165,
    "weight": 65,
    "bmi": 23.8751
  }
] 

Query: Write R code to generate a 2 by 2 frequency table of the variables 'smoke' and 'sport'. The table should be stored in a matrix called thecounts. The data set is a data.frame called "SD2011". Explicitly exclude NAs from any computation. Return the R code as JSON in an element called code. Be concise. 


"""
results2 = []
for i in range(N):
    response = ollama.chat(
        model=model_name,
        format='json', # This is the magic line
        messages=[{'role': 'user', 'content': prompt}]
    )
    # Parse the string into a real Python Dictionary
    data = json.loads(response['message']['content'])
    keep = data['code']
    #print(f"iter={i} {data['code']}\n")
    results2.append(keep)

```


```{python}
#| label: "py3"
#| include: true
#| eval: true

import ollama
import json

model_name = 'qwen3-coder:30b' #'phi4:latest'
#model_name = 'phi4:latest'
#N=10 #no. reps

prompt = """
Instruction: You are an expert statistician and programmer. Analyze the following patient records and answer the query accurately. 

Data:
[
  {
    "sex": "FEMALE",
    "age": 57,
    "agegr": "45-59",
    "placesize": "URBAN 100,000-200,000",
    "region": "Lubuskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "services for the population and transport services",
    "socprof": "RETIRED",
    "unempdur": 0,
    "income": 800,
    "marital": "MARRIED",
    "mmarr": 10,
    "ymarr": 1979,
    "ls": "PLEASED",
    "depress": 6,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "NO",
    "sport": "NO",
    "nofriend": 6,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 170,
    "weight": 89,
    "bmi": 30.7958
  },
  {
    "sex": "MALE",
    "age": 20,
    "agegr": "16-24",
    "placesize": "RURAL AREAS",
    "region": "Podlaskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": -8,
    "income": 350,
    "marital": "SINGLE",
    "ls": "MOSTLY SATISFIED",
    "depress": 0,
    "trust": "IT`S DIFFICULT TO TELL",
    "trustfam": "YES",
    "trustneigh": "NO OPINION",
    "sport": "NO",
    "nofriend": 4,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 187,
    "weight": 82,
    "bmi": 23.4493
  },
  {
    "sex": "FEMALE",
    "age": 18,
    "agegr": "16-24",
    "placesize": "URBAN 500,000 AND OVER",
    "region": "Mazowieckie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": -8,
    "marital": "SINGLE",
    "ls": "PLEASED",
    "depress": 0,
    "trust": "MOST PEOPLE CAN BE TRUSTED",
    "trustfam": "YES",
    "trustneigh": "NO",
    "sport": "NO",
    "nofriend": 20,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 165,
    "weight": 50,
    "bmi": 18.3655
  },
  {
    "sex": "FEMALE",
    "age": 78,
    "agegr": "65+",
    "placesize": "RURAL AREAS",
    "region": "Podlaskie",
    "edu": "PRIMARY/NO EDUCATION",
    "eduspec": "no specialisation",
    "socprof": "RETIRED",
    "unempdur": -8,
    "income": 900,
    "marital": "WIDOWED",
    "mmarr": 8,
    "ymarr": 1958,
    "msepdiv": 12,
    "ysepdiv": 1997,
    "ls": "MIXED",
    "depress": 16,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "NO",
    "trustneigh": "YES",
    "sport": "YES",
    "nofriend": 0,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 160,
    "weight": 78,
    "bmi": 30.4687
  },
  {
    "sex": "FEMALE",
    "age": 54,
    "agegr": "45-59",
    "placesize": "URBAN 100,000-200,000",
    "region": "Zachodnio-pomorskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "agriculture, forestry, fishing",
    "socprof": "SELF-EMPLOYED",
    "unempdur": -8,
    "income": 1500,
    "marital": "MARRIED",
    "mmarr": 6,
    "ymarr": 1980,
    "ls": "MOSTLY SATISFIED",
    "depress": 4,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "YES",
    "sport": "YES",
    "nofriend": 6,
    "smoke": "YES",
    "nociga": 20,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 158,
    "weight": 50,
    "bmi": 20.0288
  },
  {
    "sex": "MALE",
    "age": 20,
    "agegr": "16-24",
    "placesize": "URBAN 100,000-200,000",
    "region": "Slaskie",
    "edu": "SECONDARY",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": 0,
    "income": -8,
    "marital": "SINGLE",
    "ls": "PLEASED",
    "depress": 5,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "NO OPINION",
    "sport": "NO",
    "nofriend": 10,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 165,
    "weight": 65,
    "bmi": 23.8751
  }
] 

Query: Write R code to generate a 2 by 2 frequency table of the variables 'smoke' and 'sport', where this table only includes records where sex=="FEMALE" and edu=="SECONDARY". The table should be stored in a matrix called thecounts. The data set is a data.frame called "SD2011". Explicitly exclude NAs from any computation. Return the R code as JSON in an element called code. Be concise. 


"""
results3 = []
for i in range(N):
    response = ollama.chat(
        model=model_name,
        format='json', # This is the magic line
        messages=[{'role': 'user', 'content': prompt}]
    )
    # Parse the string into a real Python Dictionary
    data = json.loads(response['message']['content'])
    keep = data['code']
    #print(f"iter={i} {data['code']}\n")
    results3.append(keep)

```

```{python}
#| label: "py4"
#| include: true
#| eval: true

import ollama
import json

model_name = 'qwen3-coder:30b' #'phi4:latest'
#model_name = 'phi4:latest'
#N=10 #no. reps

prompt = """
Instruction: You are an expert statistician and programmer. Analyze the following patient records and answer the query accurately. 

Data:
[
  {
    "sex": "FEMALE",
    "age": 57,
    "agegr": "45-59",
    "placesize": "URBAN 100,000-200,000",
    "region": "Lubuskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "services for the population and transport services",
    "socprof": "RETIRED",
    "unempdur": 0,
    "income": 800,
    "marital": "MARRIED",
    "mmarr": 10,
    "ymarr": 1979,
    "ls": "PLEASED",
    "depress": 6,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "NO",
    "sport": "NO",
    "nofriend": 6,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 170,
    "weight": 89,
    "bmi": 30.7958
  },
  {
    "sex": "MALE",
    "age": 20,
    "agegr": "16-24",
    "placesize": "RURAL AREAS",
    "region": "Podlaskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": -8,
    "income": 350,
    "marital": "SINGLE",
    "ls": "MOSTLY SATISFIED",
    "depress": 0,
    "trust": "IT`S DIFFICULT TO TELL",
    "trustfam": "YES",
    "trustneigh": "NO OPINION",
    "sport": "NO",
    "nofriend": 4,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 187,
    "weight": 82,
    "bmi": 23.4493
  },
  {
    "sex": "FEMALE",
    "age": 18,
    "agegr": "16-24",
    "placesize": "URBAN 500,000 AND OVER",
    "region": "Mazowieckie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": -8,
    "marital": "SINGLE",
    "ls": "PLEASED",
    "depress": 0,
    "trust": "MOST PEOPLE CAN BE TRUSTED",
    "trustfam": "YES",
    "trustneigh": "NO",
    "sport": "NO",
    "nofriend": 20,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 165,
    "weight": 50,
    "bmi": 18.3655
  },
  {
    "sex": "FEMALE",
    "age": 78,
    "agegr": "65+",
    "placesize": "RURAL AREAS",
    "region": "Podlaskie",
    "edu": "PRIMARY/NO EDUCATION",
    "eduspec": "no specialisation",
    "socprof": "RETIRED",
    "unempdur": -8,
    "income": 900,
    "marital": "WIDOWED",
    "mmarr": 8,
    "ymarr": 1958,
    "msepdiv": 12,
    "ysepdiv": 1997,
    "ls": "MIXED",
    "depress": 16,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "NO",
    "trustneigh": "YES",
    "sport": "YES",
    "nofriend": 0,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 160,
    "weight": 78,
    "bmi": 30.4687
  },
  {
    "sex": "FEMALE",
    "age": 54,
    "agegr": "45-59",
    "placesize": "URBAN 100,000-200,000",
    "region": "Zachodnio-pomorskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "agriculture, forestry, fishing",
    "socprof": "SELF-EMPLOYED",
    "unempdur": -8,
    "income": 1500,
    "marital": "MARRIED",
    "mmarr": 6,
    "ymarr": 1980,
    "ls": "MOSTLY SATISFIED",
    "depress": 4,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "YES",
    "sport": "YES",
    "nofriend": 6,
    "smoke": "YES",
    "nociga": 20,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 158,
    "weight": 50,
    "bmi": 20.0288
  },
  {
    "sex": "MALE",
    "age": 20,
    "agegr": "16-24",
    "placesize": "URBAN 100,000-200,000",
    "region": "Slaskie",
    "edu": "SECONDARY",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": 0,
    "income": -8,
    "marital": "SINGLE",
    "ls": "PLEASED",
    "depress": 5,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "NO OPINION",
    "sport": "NO",
    "nofriend": 10,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 165,
    "weight": 65,
    "bmi": 23.8751
  }
] 

Query: Write R code to generate a 2 by 2 frequency table of the variables 'smoke' and 'sport', where this table only includes records where sex=="FEMALE" and edu=="SECONDARY". Compute the row percentages from this 2 by 2 table and store it a matrix called thepercs. The data set is a data.frame called "SD2011". Explicitly exclude NAs from any computation. Return the R code as JSON in an element called code. Be concise. 


"""
results4 = []
for i in range(N):
    response = ollama.chat(
        model=model_name,
        format='json', # This is the magic line
        messages=[{'role': 'user', 'content': prompt}]
    )
    # Parse the string into a real Python Dictionary
    data = json.loads(response['message']['content'])
    keep = data['code']
    #print(f"iter={i} {data['code']}\n")
    results4.append(keep)

```


```{python}
#| label: "py5"
#| include: true
#| eval: true

import ollama
import json

model_name = 'qwen3-coder:30b' #'phi4:latest'
#model_name = 'phi4:latest'
#N=10 #no. reps

prompt = """
Instruction: You are an expert statistician and programmer. Analyze the following patient records and answer the query accurately. 

Data:
[
  {
    "sex": "FEMALE",
    "age": 57,
    "agegr": "45-59",
    "placesize": "URBAN 100,000-200,000",
    "region": "Lubuskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "services for the population and transport services",
    "socprof": "RETIRED",
    "unempdur": 0,
    "income": 800,
    "marital": "MARRIED",
    "mmarr": 10,
    "ymarr": 1979,
    "ls": "PLEASED",
    "depress": 6,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "NO",
    "sport": "NO",
    "nofriend": 6,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 170,
    "weight": 89,
    "bmi": 30.7958
  },
  {
    "sex": "MALE",
    "age": 20,
    "agegr": "16-24",
    "placesize": "RURAL AREAS",
    "region": "Podlaskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": -8,
    "income": 350,
    "marital": "SINGLE",
    "ls": "MOSTLY SATISFIED",
    "depress": 0,
    "trust": "IT`S DIFFICULT TO TELL",
    "trustfam": "YES",
    "trustneigh": "NO OPINION",
    "sport": "NO",
    "nofriend": 4,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 187,
    "weight": 82,
    "bmi": 23.4493
  },
  {
    "sex": "FEMALE",
    "age": 18,
    "agegr": "16-24",
    "placesize": "URBAN 500,000 AND OVER",
    "region": "Mazowieckie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": -8,
    "marital": "SINGLE",
    "ls": "PLEASED",
    "depress": 0,
    "trust": "MOST PEOPLE CAN BE TRUSTED",
    "trustfam": "YES",
    "trustneigh": "NO",
    "sport": "NO",
    "nofriend": 20,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 165,
    "weight": 50,
    "bmi": 18.3655
  },
  {
    "sex": "FEMALE",
    "age": 78,
    "agegr": "65+",
    "placesize": "RURAL AREAS",
    "region": "Podlaskie",
    "edu": "PRIMARY/NO EDUCATION",
    "eduspec": "no specialisation",
    "socprof": "RETIRED",
    "unempdur": -8,
    "income": 900,
    "marital": "WIDOWED",
    "mmarr": 8,
    "ymarr": 1958,
    "msepdiv": 12,
    "ysepdiv": 1997,
    "ls": "MIXED",
    "depress": 16,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "NO",
    "trustneigh": "YES",
    "sport": "YES",
    "nofriend": 0,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 160,
    "weight": 78,
    "bmi": 30.4687
  },
  {
    "sex": "FEMALE",
    "age": 54,
    "agegr": "45-59",
    "placesize": "URBAN 100,000-200,000",
    "region": "Zachodnio-pomorskie",
    "edu": "VOCATIONAL/GRAMMAR",
    "eduspec": "agriculture, forestry, fishing",
    "socprof": "SELF-EMPLOYED",
    "unempdur": -8,
    "income": 1500,
    "marital": "MARRIED",
    "mmarr": 6,
    "ymarr": 1980,
    "ls": "MOSTLY SATISFIED",
    "depress": 4,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "YES",
    "sport": "YES",
    "nofriend": 6,
    "smoke": "YES",
    "nociga": 20,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "NONE",
    "height": 158,
    "weight": 50,
    "bmi": 20.0288
  },
  {
    "sex": "MALE",
    "age": 20,
    "agegr": "16-24",
    "placesize": "URBAN 100,000-200,000",
    "region": "Slaskie",
    "edu": "SECONDARY",
    "eduspec": "no specialisation",
    "socprof": "PUPIL OR STUDENT",
    "unempdur": 0,
    "income": -8,
    "marital": "SINGLE",
    "ls": "PLEASED",
    "depress": 5,
    "trust": "ONE CAN`T BE TOO CAREFUL",
    "trustfam": "YES",
    "trustneigh": "NO OPINION",
    "sport": "NO",
    "nofriend": 10,
    "smoke": "NO",
    "nociga": -8,
    "alcabuse": "NO",
    "alcsol": "NO",
    "workab": "NO",
    "wkabdur": "-8",
    "wkabint": "NO",
    "englang": "ACTIVE",
    "height": 165,
    "weight": 65,
    "bmi": 23.8751
  }
] 

Query: Write R code to generate a 2 by 2 frequency table of the variables 'smoke' and 'sport', where this table only includes records where sex=="FEMALE" and edu=="SECONDARY". Compute the column percentages from this 2 by 2 table and store it a matrix called thepercs. The data set is a data.frame called "SD2011". Explicitly exclude NAs from any computation. Return the R code as JSON in an element called code. Be concise. 


"""
results5 = []
for i in range(N):
    response = ollama.chat(
        model=model_name,
        format='json', # This is the magic line
        messages=[{'role': 'user', 'content': prompt}]
    )
    # Parse the string into a real Python Dictionary
    data = json.loads(response['message']['content'])
    keep = data['code']
    #print(f"iter={i} {data['code']}\n")
    results5.append(keep)

```
```{r}
results1<-py$results1
results2<-py$results2
results3<-py$results3
results4<-py$results4
results5<-py$results5
save(results1,results2,results3,results4,results5,file="res.RData")

```

# Results 1 - summary stats
```{r}

safe_run_list <- function(code) {
  tryCatch({
    exprs <- parse(text = code);
    all_results <- sapply(exprs, eval);
    return(all_results)
  }, error = function(e) {
    paste("Error in generated code:", e$message)
  })
}
safe_run_list(py$results1[1])

#true results in ex1_res[[1]] [[2]] [[3]]
cnt1<-0;
for(i in 1:length(py$results1)){
  tmp<-safe_run_list(py$results1[i])
  if(ex1_res[[1]]==tmp[[1]] && 
     ex1_res[[2]]==tmp[[2]] &&
     ex1_res[[3]]==tmp[[3]]){cnt1<-cnt1+1;}
}

cat("out of ",length(py$results1), cnt1," are correct\n")
```

# Results 2 -  2x2
```{r}

safe_run<- function(code) {
  tryCatch({
    all_results <- eval(parse(text = code));
    return(all_results)
  }, error = function(e) {
    paste("Error in generated code:", e$message)
  })
}
safe_run(py$results2[1])


#true results in ex1_res[[1]] [[2]] [[3]]
cnt2<-0;
for(i in 1:length(py$results2)){
  tmp<-safe_run(py$results2[i])
   if(is.matrix(tmp) && nrow(tmp)==2 && ncol(tmp)==2){
  cell_cnt<-0;
  for(r in 1:2){
    for(c in 1:2){
      if(ex2[r,c]==tmp[r,c]){cell_cnt<-cell_cnt+1;}
    }
  }
  if(cell_cnt==4){cnt2<-cnt2+1}
   }
}

cat("out of ",length(py$results2), cnt2," are correct\n")

```

# Results 3 - 2x2 filter
```{r}

safe_run<- function(code) {
  tryCatch({
    all_results <- eval(parse(text = code));
    return(all_results)
  }, error = function(e) {
    paste("Error in generated code:", e$message)
  })
}
safe_run(py$results3[1])


#true results in ex1_res[[1]] [[2]] [[3]]
cnt3<-0;
for(i in 1:length(py$results3)){
  tmp<-safe_run(py$results3[i])
  if(is.matrix(tmp) && nrow(tmp)==2 && ncol(tmp)==2){
    
  cell_cnt<-0;
  for(r in 1:2){
    for(c in 1:2){
      if(ex3[r,c]==tmp[r,c]){cell_cnt<-cell_cnt+1;}
    }
  }
  if(cell_cnt==4){cnt3<-cnt3+1}
  }
  }

cat("out of ",length(py$results3), cnt3," are correct\n")

```

# Results 4 -  row %
```{r}

safe_run<- function(code) {
  tryCatch({
    all_results <- eval(parse(text = code));
    return(all_results)
  }, error = function(e) {
    paste("Error in generated code:", e$message)
  })
}
safe_run(py$results4[1])


#true results in ex1_res[[1]] [[2]] [[3]]
cnt4<-0;
for(i in 1:length(py$results4)){
  tmp<-safe_run(py$results4[i])
  if(is.matrix(tmp) && nrow(tmp)==2 && ncol(tmp)==2){
  cell_cnt<-0;
  for(r in 1:2){
    for(c in 1:2){
      if(100*ex3_row[r,c]==tmp[r,c]){cell_cnt<-cell_cnt+1;}
    
  }}
  if(cell_cnt==4){cnt4<-cnt4+1}
  }
}

cat("out of ",length(py$results4), cnt4," are correct\n")

```
# Results 5 - col %
```{r}

safe_run<- function(code) {
  tryCatch({
    all_results <- eval(parse(text = code));
    return(all_results)
  }, error = function(e) {
    paste("Error in generated code:", e$message)
  })
}
safe_run(py$results5[1])


#true results in ex1_res[[1]] [[2]] [[3]]
cnt5<-0;
for(i in 1:length(py$results5)){
  tmp<-safe_run(py$results5[i])
  if(is.matrix(tmp) && nrow(tmp)==2 && ncol(tmp)==2){
  cell_cnt<-0;
  for(r in 1:2){
    for(c in 1:2){
      if(100*ex3_col[r,c]==tmp[r,c]){cell_cnt<-cell_cnt+1;}
    
  }}
  if(cell_cnt==4){cnt5<-cnt5+1}
  }
}

cat("out of ",length(py$results5), cnt5," are correct\n")

```
```{r}
save.image("all.RData")
```




## the end
